- Rakefile
When docker-compose is started as a child process, it continues to run
even after the rake task has exited. This is because it "traps" the
interrupt (`CTRL + C`) and Ruby doesn't wait for the process to really end.
Switch `system` usage to `spawn` like we also do for the agent
integration test suite. Connect it to the parent process STDIN, STDOUT
and STDERR so that it has the same behavior as `system`.
Except, wait for the process to really end. Use `Process.wait2` to wait
for the child process to quit. But also register the PID on the
`child_processes` array. Then loop over this array of process in our own
"trap" on interrupt and wait for the process to really end.
If a user presses `CTRL + C` again (another interrupt) docker-compose
will continue to "kill" the process instead and exit …
> Wait for child process to gracefully exit

- ruby/single-task/Dockerfile
- ruby/single-task/README.md
- ruby/single-task/app/Gemfile
- ruby/single-task/app/Gemfile.lock
- ruby/single-task/app/app.rb
- ruby/single-task/commands/boot.sh
- ruby/single-task/commands/console.sh
- ruby/single-task/commands/diagnose.sh
- ruby/single-task/docker-compose.yml
Simple Ruby app to use in the most basic of testing.
Add object integration to test the keyword argument forwarding in Ruby
3.0 for this PR: https://github.com/appsignal/appsignal-ruby/pull/692
> Add Ruby single task app

- support/processmon/Dockerfile
I created an issue for this, but then it didn't take that long to fix. Fixes #65.
> Fix Processmon build failure in tests

- .semaphore/semaphore.yml
- elixir/plug/Dockerfile
- elixir/plug/README.md
- elixir/plug/app/.formatter.exs
- elixir/plug/app/.gitignore
- elixir/plug/app/README.md
- elixir/plug/app/lib/plug_example.ex
- elixir/plug/app/lib/plug_example/application.ex
- elixir/plug/app/mix.exs
- elixir/plug/app/test/plug_example_test.exs
- elixir/plug/app/test/test_helper.exs
- elixir/plug/commands/console
- elixir/plug/commands/diagnose
- elixir/plug/commands/run
- elixir/plug/docker-compose.yml
Add the simplest Plug example app, to use for testing things like https://github.com/appsignal/appsignal-elixir-phoenix/issues/57.
> Add Plug example app

- .semaphore/semaphore.yml
- go/beego/app/main.go
- go/beego/docker-compose.yml
- go/go-gin-mysql/app/main.go
- go/go-gin-mysql/docker-compose.yml
- go/gorilla-mux-mysql-redis-mongo/app/main.go
- go/gorilla-mux-mysql-redis-mongo/docker-compose.yml
Add the three Go test setups to CI. All setups are CI covered now.
Closes #92
> Add Golang setups to CI

- python/django4-celery/app/appsignal_python_opentelemetry/templates/home.html
- python/django4-celery/app/appsignal_python_opentelemetry/urls.py
- python/django4-celery/app/appsignal_python_opentelemetry/views.py
Add more examples of custom instrumentation and custom errors to cover more scenarios for testing.
> Add Django routes with custom instrumentation

- .semaphore/semaphore.yml
- nodejs/v3/nextjs-appdir/app/package-lock.json
- nodejs/v3/nextjs-noappdir/app/package-lock.json
They weren't part of the CI, so let's add them.
> Add Next.js apps to CI

- elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/router.ex
- elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/schema.ex
- elixir/phoenix-example/app/mix.exs
Add Absinthe endpoint for testing the Absinthe integration.
> Add Absinthe endpoint

- nodejs/v3/express-yoga/app/package-lock.json
- nodejs/v3/express-yoga/app/package.json
- nodejs/v3/express-yoga/app/src/app.ts
Add a route focussed on custom instrumentation so it's easier to test without setting up anything manually every time.
Following the Elixir Phoenix app's `/custom_instrumentation` route naming.
Add a child span so we can also test if that works as expected.
> Add custom instrumentation route for yoga app

- ruby/rails7-sidekiq/app/Gemfile
- ruby/rails7-sidekiq/app/Gemfile.lock
- ruby/rails7-sidekiq/app/app/channels/chat_room_channel.rb
- ruby/rails7-sidekiq/app/app/controllers/chat_messages_controller.rb
- ruby/rails7-sidekiq/app/app/controllers/chat_rooms_controller.rb
- ruby/rails7-sidekiq/app/app/javascript/application.js
- ruby/rails7-sidekiq/app/app/javascript/channels/chat_room_channel.js
- ruby/rails7-sidekiq/app/app/javascript/channels/consumer.js
- ruby/rails7-sidekiq/app/app/javascript/channels/index.js
- ruby/rails7-sidekiq/app/app/models/chat_message.rb
- ruby/rails7-sidekiq/app/app/models/chat_room.rb
- ruby/rails7-sidekiq/app/app/views/chat_rooms/_chat_room.html.erb
- ruby/rails7-sidekiq/app/app/views/chat_rooms/index.html.erb
- ruby/rails7-sidekiq/app/app/views/chat_rooms/show.html.erb
- ruby/rails7-sidekiq/app/app/views/examples/index.html.erb
- ruby/rails7-sidekiq/app/config/cable.yml
- ruby/rails7-sidekiq/app/config/importmap.rb
- ruby/rails7-sidekiq/app/config/routes.rb
- ruby/rails7-sidekiq/app/db/migrate/20230818075259_create_chat_rooms.rb
- ruby/rails7-sidekiq/app/db/migrate/20230818080806_create_chat_messages.rb
- ruby/rails7-sidekiq/app/db/schema.rb
Add it to the Sidekiq one, as it's the most complete test app.
- [Related Slack thread](https://appsignal.slack.com/archives/C7XHXQ7N0/p1692334621256969)
- [Related Intercom conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/unassigned/conversation/16410700236059?view=List)
> Add chat room to Rails 7 app with ActionCable

- nodejs/v3/nextjs-noappdir/Dockerfile
- nodejs/v3/nextjs-noappdir/README.md
- nodejs/v3/nextjs-noappdir/commands/run
- nodejs/v3/nextjs/commands/run
Help debug issue https://github.com/appsignal/support/issues/282
[skip review]
> Run the Next.js page router app in production

- python/flask/app/app.py
Requires https://github.com/appsignal/appsignal-python/pull/121
﻿## Add endpoint to test custom metrics
Send values for all the different types of metrics we support.
> Add flask custom metrics endpoint

- elixir/phoenix-example/Dockerfile
- ruby/jruby-rails6/Dockerfile
- ruby/rails6-mongo/Dockerfile
- ruby/rails6-mysql/Dockerfile
- ruby/rails6-sequel/Dockerfile
- ruby/rails6-shakapacker/Dockerfile
- ruby/rails6-sidekiq/Dockerfile
- ruby/rails7-delayed-job/Dockerfile
- ruby/rails7-sidekiq/Dockerfile
Some apps have trouble installing older versions of Node.js locally and/or on CI.
[skip review]
> Update Node.js for all apps

- ruby/rails6-sequel/commands/run
Mark which type of file it is. Also helps with editor file type detection.
[skip review]
> Update Rails 6 Sequel app

- nodejs/v3/express-redis/app/src/app.ts
Make testing easier this scenario by adding a type of Express route with a parameter in it.
[skip review]
> Add route with route parameter to Express test app

- .semaphore/semaphore.yml
- Rakefile
- ruby/rails7-postgres/.gitignore
- ruby/rails7-postgres/README.md
- ruby/rails7-postgres/app/Gemfile.lock
- ruby/rails7-postgres/docker-compose.yml
- ruby/rails7-postgres/hooks/before_build
- ruby/rails7-postgres/vector/vector.toml.template
Add a hook system so that we can run custom commands before the app is built. In this case to generate a `vector.toml` config file.
Related to https://github.com/appsignal/appsignal-processor-rs/issues/1069
> Vector to Rails 6 postgres app for testing

- elixir/phoenix-example/Dockerfile
- elixir/phoenix-example/app/assets/package-lock.json
- elixir/phoenix-example/app/assets/package.json
- elixir/phoenix-example/app/config/runtime.exs
- elixir/phoenix-example/app/lib/appsignal_phoenix_example/application.ex
See https://github.com/appsignal/appsignal-elixir/pull/893 for the corresponding implementation.
> Use Erlang :logger handler in Phoenix test setup

- python/flask/app/app.py
See https://github.com/appsignal/appsignal-python/pull/199 for context.
> Add minutely probes to Flask test setup

- elixir/phoenix-oban/app/lib/test_app/user.ex
- elixir/phoenix-oban/app/lib/test_app_web/controllers/page_controller.ex
- elixir/phoenix-oban/app/lib/test_app_web/controllers/page_html/home.html.heex
- elixir/phoenix-oban/app/lib/test_app_web/router.ex
- elixir/phoenix-oban/app/lib/test_app_web/workers/user_worker.ex
- elixir/phoenix-oban/app/priv/repo/migrations/20240404094715_create_users.exs
Try to break it for issue
https://github.com/appsignal/support/issues/317
[skip review]
> Add Oban job with lots of queries

- nodejs/express-redis/app/src/app.ts
See also [agent extractor](https://github.com/appsignal/appsignal-agent/pull/1146) and [integration change](https://github.com/appsignal/appsignal-nodejs/pull/1052).
> Add `/fetch` endpoint to Express + Redis

- python/flask-sqlalchemy/app/requirements.txt
- python/flask/app/requirements.txt
Part of https://github.com/appsignal/appsignal-python/issues/169.
> Update to Flask 3

- .semaphore/semaphore.yml
- ruby/rack/Dockerfile
- ruby/rack/app/Gemfile
- ruby/rack/app/Gemfile.lock
- ruby/rack/app/app.rb
- ruby/rack/app/config.ru
- ruby/rack/app/processmon.toml
- ruby/rack/commands/run
- ruby/rack/docker-compose.yml
We didn't have a Rack app yet. Add one that follows our new Ruby gem docs and uses the EventHandler.
[skip review]
> Add Ruby Rack test app

- .semaphore/semaphore.yml
- ruby/grape/Dockerfile
- ruby/grape/app/Gemfile
- ruby/grape/app/Gemfile.lock
- ruby/grape/app/api.rb
- ruby/grape/app/config.ru
- ruby/grape/app/processmon.toml
- ruby/grape/commands/run
- ruby/grape/docker-compose.yml
Add a basic Ruby grape app with an in memory data store for post objects.
Not overcomplicating things and added some curl commands in the view to perform actions on the API.
[skip review]
> Add Ruby grape app

- python/flask-pika/Dockerfile
- python/flask-pika/app/.gitignore
- python/flask-pika/app/__appsignal__.py
- python/flask-pika/app/app.py
- python/flask-pika/app/pika_consumer.py
- python/flask-pika/app/processmon.toml
- python/flask-pika/app/requirements.txt
- python/flask-pika/commands/run
- python/flask-pika/docker-compose.yml
Add test setup for Flask + Pika. The consumer works as an independent worker.
Part of https://github.com/appsignal/appsignal-python/issues/181
> Flask-Pika app

- Rakefile
> Always switch branches on integrations clone

- ruby/sinatra-puma/app/app.rb
See https://github.com/appsignal/appsignal-ruby/pull/1210.
> Add multiple errors endpoint

- elixir/phoenix-example/app/processmon.toml
- elixir/phoenix-oban/app/processmon.toml
It would constantly restart the app.
[skip review]
> Fix Elixir processmon ignore directories

- nodejs/express-redis/app/src/app.ts
See https://github.com/appsignal/appsignal-nodejs/pull/1123.
> Add heartbeat check-ins `express-redis` endpoint

- elixir/plug/app/lib/plug_example.ex
- elixir/plug/app/lib/plug_example/application.ex
See https://github.com/appsignal/appsignal-elixir/pull/962.
> Add heartbeat check-ins `plug` endpoint

- nodejs/fastify/app/src/app.ts
- nodejs/fastify/commands/run
Add Pino logging with the Appsignal transport to the Fastify app
> Pino logging with Fastify

- nodejs/express-apollo/commands/run
- nodejs/express-mongoose/commands/run
- nodejs/express-redis-alpine/commands/run
- nodejs/express-yoga/commands/run
- nodejs/koa-mongo/commands/run
- nodejs/koa-mysql/commands/run
- nodejs/nestjs-prisma/commands/run
- nodejs/remix/commands/run
- nodejs/restify/commands/run
I removed `script/setup` in this commit when moving the Node.js package build to GitHub Actions
https://github.com/appsignal/appsignal-nodejs/commit/4695a6b81587021d79fa32b5f49a3f33f76d7a1a
[skip review]
> Fix the Node.js apps builds

- vector/mongodb/docker-compose.yml
- vector/mongodb/vector/vector.toml
> Vector update

- nodejs/fastify/app/src/app.ts
See https://github.com/appsignal/appsignal-nodejs/pull/1151 for context.
> Use Pino transport as a transport

- .semaphore/semaphore.yml
- nodejs/nestjs-11/Dockerfile
- nodejs/nestjs-11/app/.eslintrc.js
- nodejs/nestjs-11/app/.gitignore
- nodejs/nestjs-11/app/.prettierrc
- nodejs/nestjs-11/app/appsignal.cjs
- nodejs/nestjs-11/app/nest-cli.json
- nodejs/nestjs-11/app/package-lock.json
- nodejs/nestjs-11/app/package.json
- nodejs/nestjs-11/app/processmon.toml
- nodejs/nestjs-11/app/src/app.controller.spec.ts
- nodejs/nestjs-11/app/src/app.controller.ts
- nodejs/nestjs-11/app/src/app.module.ts
- nodejs/nestjs-11/app/src/app.service.ts
- nodejs/nestjs-11/app/src/main.ts
- nodejs/nestjs-11/app/test/app.e2e-spec.ts
- nodejs/nestjs-11/app/test/jest-e2e.json
- nodejs/nestjs-11/app/tsconfig.build.json
- nodejs/nestjs-11/app/tsconfig.json
- nodejs/nestjs-11/commands/run
- nodejs/nestjs-11/docker-compose.yml
Help debug a support issue, add a basic test app.
[skip review]
> Add Nest.js v11 test app

- python/django5-celery-collector/app/appsignal_python_opentelemetry/opentelemetry.py
- python/django5-celery-collector/app/appsignal_python_opentelemetry/views.py
- Fix config option name.
- Update custom query parameter attribute name.
- Add a header custom attribute too.
[skip review]
> Update Python collector custom attributes

- java/spring-agent-collector/app/build.gradle.kts
- java/spring-agent-collector/app/src/main/java/io/opentelemetry/example/graal/Controller.java
- java/spring-agent-collector/app/src/main/java/io/opentelemetry/example/graal/ElasticsearchService.java
- java/spring-agent-collector/docker-compose.yml
Add an example on how to add the ElasticSearch database and make a query to it. This has some boilerplate to generate some dummy data in it.
The ElasticSearch package has OpenTelemetry instrumentation, so adding it will also add instrumentation for ElasticSearch.
> Add ElasticSearch example to Java app

- CLAUDE.md
Help development using Claude by adding some project setup and instructions on how to start the app and how to test it.
Hopefully this will help others that are trying to use it while making changes to this project.
[skip ci]
> Add CLAUDE.md instructions file

- go/go-gin-mysql/Dockerfile
- go/gorilla-mux-mysql-redis-mongo/Dockerfile
- python/django4-asgi/Dockerfile
- python/django4-wsgi/Dockerfile
- python/fastapi-databases/Dockerfile
- python/flask-pika/Dockerfile
- python/flask-sqlalchemy/Dockerfile
This fixes an issue where the Docker image fails to build locally. It is unclear why it's not failing in CI.
> Move `buster` test setups to `bullseye`
