appsignal/test-setups

ruby/rails-postgres/app/Gemfile
ruby/rails-postgres/app/Gemfile.lock
ruby/rails-postgres/app/config/database.yml
ruby/rails-postgres/app/db/schema.rb
ruby/rails-postgres/commands/boot.sh

The rails postgres app didn't actually use the postgres database that
was spun up alongside it. It was using sqlite.
The app now uses the PostgreSQL database and runs the migrations
automatically on boot so the user doesn't have to run the manually after
start.

Update rails-postgres example to use PostgreSQL

---

README.md
Rakefile
elixir/alpine-release/docker-compose.yml
elixir/phoenix-example/docker-compose.yml
nodejs/express-postgres/docker-compose.yml
ruby/rails-postgres/commands/boot.sh
ruby/rails-postgres/docker-compose.yml
ruby/shoryuken/app/Gemfile.lock
ruby/shoryuken/docker-compose.yml
ruby/single-task/docker-compose.yml
support/templates/README.md.erb
support/templates/skeleton/docker-compose.yml.erb

Port 4001 should not conflict with most apps that can also run on the
host machine at the same time.
I also removed all the other `ports:` statements for databases from the
`docker-compose.yml` files. The `ports:` statements expose ports from
the container to the host server, and for databases this is not required
to function. All containers are on their own network and can communicate
with each other without explicitly exposing ports between containers.
Closes #10

Make default app port 4001

---

Rakefile
elixir/alpine-release/docker-compose.yml
elixir/phoenix-example/docker-compose.yml
nodejs/express-postgres/docker-compose.yml
ruby/rails-postgres/docker-compose.yml
ruby/shoryuken/docker-compose.yml
ruby/single-task/docker-compose.yml
support/templates/skeleton/docker-compose.yml.erb

Instead using using `docker build` and tagging an image manually, use
`docker-compose build` and let it tag the image based on the image name
defined in the `docker-compose.yml` file.
When I was adding a react app using the JavaScript integration I moved
it from the `nodejs` to the `javascript` directory, and didn't realize
the docker image was automatically tagged based on the directory name
and the image name referred to in the `docker-compose.yml` file didn't
match anymore. I was building a new image but still testing against the
old image.
This change moves all that config to the `docker-compose.yml` file and
doesn't base the image name on the app directory anymore, only during
`rake app:new` when the `docker-compose.yml` is generated. By specifying
`build: .` in the …

Use docker compose to build images

---

Rakefile
elixir/alpine-release/docker-compose.yml
elixir/phoenix-example/docker-compose.yml
javascript/react/docker-compose.yml
javascript/webpack/docker-compose.yml
nodejs/express-postgres/docker-compose.yml
nodejs/next-js/docker-compose.yml
ruby/rails-postgres/docker-compose.yml
ruby/rails-sidekiq/docker-compose.yml
ruby/shoryuken/docker-compose.yml
ruby/single-task/docker-compose.yml
support/templates/skeleton/docker-compose.yml.erb

Docker volume performance on macOS is not great. Apps that rely on a lot
of file system interaction (reading and writing) are much slower on the
mounted volume than the host system.
Use NFS volumes to speed up the mounted volumes. NFS seems much faster
for apps such as Node.js, as per a very basic speed test comparison:
Docker volume vs NFS volume speed test running `yarn install` in
`appsignal-javascript/packages/javascript`, lower is better:
- standard volume: 307.25s
- NFS volume: 122.22s
No significant increase of build time for `yarn build` for the same
package, lower is better:
- standard volume: 33.59s
- NFS volume: 28.97s
Closes #17 
On macOS there are some additional steps required to set up NFS volumes
on the system. I've added this in an automated way to the
`app:prepare_nfs` …

Use NFS volumes to speed up builds

---

nodejs/koa/app/app.js

Due to the addition of new error tracking helpers in NodeJS library,
NextJS test setup needed and update to stop using `span.addError()` and
start using `tracer.setError()`
Please, merge after the release of https://github.com/appsignal/appsignal-nodejs/pull/446

Make Koa setup compatible with error helpers

---

elixir/alpine-release/commands/console
elixir/phoenix-example/app/processmon.toml
elixir/phoenix-example/commands/console

The current implementation of the `app:console` command for the Phoenix application attempts to call `iex -S mix phx.server`. This command would start a new server and provide you with a shell to it, but since `app:console` is a `docker exec` command, it must be executed after `app:up` (`docker run`), which itself starts a server. Since a server is already running, the port is already in use and the console-spawned server fails to start. Even if this worked, spawning a new server with a console attached to it is not the same as attaching a console to the already running server.
For the `phoenix-example` test setup, this commit changes it so that the server spawned on `app:up` has an Erlang node name. This makes it possible for `app:console` to attach an `iex` remote shell to that node. …

Use Elixir remote shell for `app:console`

---

javascript/react/app/package.json
javascript/react/app/src/App.js
javascript/react/commands/run

This makes testing against the local package possible.
This way we can actually track the errors in the way the
`@appsignal/react` package provides. Remove the demo call, because we
should test the render errors instead.
[skip review]

Update react app

---

javascript/react/app/src/App.js

Throw an error in the React test app when a user click the "Trigger
error" button.
This needs to be done in the render function, rather than the
`triggerError` event handler. Errors in event handlers are not picked up
by the ErrorBoundary. This is how it works in React:
https://reactjs.org/docs/error-boundaries.html#how-about-event-handlers
[skip review]

Track errors in React using ErrorBoundary

---

ruby/rails-sidekiq/Dockerfile

Something seems to have changed in one of the dependencies (`@npmcli/fs`) and they've dropped Node 15 support. I'm guessing it relates to [Node 15 no longer being supported, as it's an odd release](https://nodejs.org/en/about/releases/). I've downgraded the project to Node 14, which fixes the issue with the dependencies and allows the app to run and the tests to pass.
A more in-depth re-building of this and other sample projects, as @tombruijn mentioned in a comment in #42, would be nice, but for now this fixes the issue with the tests, and thus fixes #42.

Downgrade rails-sidekiq to Node 14.x

---

elixir/alpine-release/Dockerfile
elixir/alpine-release/app/assets/package-lock.json
elixir/alpine-release/app/assets/package.json
elixir/alpine-release/app/mix.exs

Updates the `alpine-release` version to the latest 1.13 version, as the `postgrex` package seems to have dropped support for 1.10.
Fixes #50.

Update `alpine-release` Elixir to 1.13

---

javascript/ember/commands/run
javascript/react/commands/run
javascript/typescript-angular/commands/run
javascript/vanilla/commands/run
javascript/vue-2/commands/run.sh
javascript/vue-3/commands/run.sh
javascript/webpack/commands/run

[As suggested by @tombruijn in #51](https://github.com/appsignal/test-setups/pull/51#discussion_r793448102), pass to `mono build` the list of packages that are actually needed, instead of building the whole integration. In addition, ensure that `@appsignal/types` and `@appsignal/core` are always built and linked with `yarn link`, as the other packages depend on them.

Build only needed Javascript packages

---

.semaphore/semaphore.yml
ruby/jruby-rails6/app/config/application.rb

The jruby-rails6 was running the Padrino tests by mistake. This commits
updates it to run its own tests.
[skip review]

Fix jruby-Rails6 CI

---

javascript/vanilla/README.md
javascript/vanilla/app/build.js
javascript/vanilla/app/package.json
javascript/vanilla/app/src/app.js
javascript/vanilla/app/src/appsignal.js
javascript/vanilla/app/src/index.html
javascript/vanilla/app/src/something.html
javascript/vanilla/app/src/style.css

This commit adds support for the framework-independent plugins to the vanilla test setup. It provides a simple interface for testing the behaviour of `plugin-window-events`, `plugin-path-decorator`, `plugin-breadcrumbs-console` and `plugin-breadcrumbs-network`.
Since the console breadcrumbs plugin instruments `console.log`, the feedback from the test buttons is now shown through a dedicated "Output" section in the page.
Since there are many different errors reported from the same buttons in the same app, each error now has its own named subclass. This makes it easy to tell them apart in AppSignal's UI.
This should allow for proper testing of appsignal/appsignal-javascript#575.

Add plugins to the vanilla test setup

---

elixir/phoenix-example/app/lib/appsignal_phoenix_example/application.ex
elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/controllers/page_controller.ex
elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/router.ex
elixir/phoenix-example/app/mix.exs

Adds a test endpoint for Finch to the `phoenix-example` app. Useful for reviewing appsignal/appsignal-elixir#794.

Add Finch test endpoint

---

ruby/webmachine/app/Gemfile

This fixes the failure to run in the `ruby/webmachine` test setup on newer Ruby versions.

Fix Webmachine test setup

---

nodejs/esbuild-express/commands/run
nodejs/express-apollo/commands/prepare
nodejs/express-postgres/commands/run
nodejs/express-redis/commands/run
nodejs/koa/commands/prepare
nodejs/next-js/commands/prepare

These apps are designed to work on Node.js 2.x, not Node.js 3.x. We have a different set of apps as integration tests for 3.x in the repository itself.

Fix Node.js apps by pinning them to 2.4 branch

---

ruby/rails6-sidekiq/app/Gemfile

Lock the version to version 6 so that it doesn't use version 7.

Fix Sidekiq app using version 6

---

.semaphore/semaphore.yml

Build processmon just once. It's a waste of resources to build it for every app test and for every build. It caches the build artifact and restores it again for every build.
If we need to use a new processmon version, update the CACHE_VERSION env var value.

Build processmon once in the CI

---

nodejs/esbuild-express/app/src/app.js
nodejs/esbuild-express/docker-compose.yml
nodejs/express-postgres/app/app.js
nodejs/express-postgres/docker-compose.yml
nodejs/express-redis/app/app.js
nodejs/express-redis/docker-compose.yml
nodejs/koa/app/app.js
nodejs/koa/docker-compose.yml
support/templates/skeleton/docker-compose.yml.erb

The difference between the Docker compose internal network port and the port exposed to the outside has tripped me up more than once. For instance when the container output says something like: "The app is ready at 127.0.0.0:3000", but it's not.
Let's use the same port everywhere. Configure the PORT env var by default, because we need to configure the port for some apps manually anyway, and others listen the this PORT env var.

Configure app port to always be 4001

---

.semaphore/semaphore.yml
nodejs/express-redis-v3-alpine/Dockerfile
nodejs/express-redis-v3-alpine/README.md
nodejs/express-redis-v3-alpine/app/app.js
nodejs/express-redis-v3-alpine/app/appsignal.cjs
nodejs/express-redis-v3-alpine/app/package.json
nodejs/express-redis-v3-alpine/app/processmon.toml
nodejs/express-redis-v3-alpine/app/views/index.pug
nodejs/express-redis-v3-alpine/app/views/new.pug
nodejs/express-redis-v3-alpine/commands/run
nodejs/express-redis-v3-alpine/docker-compose.yml
nodejs/express-redis-v3/docker-compose.yml

This makes it clearer to see which apps' tests are being ran.
Nothing interesting to see in this commit -- this is a separate
commit so the diff with the next commit is nicer.
This commit actually implements the changes needed to use an
Alpine image instead of a Debian-based image.

Add Express + Redis + V3 + Alpine test setup

---

standalone/nginx/commands/.gitkeep
standalone/nginx/docker-compose.yml
standalone/nginx/nginx/Dockerfile
standalone/nginx/nginx/conf.d/appsignal.conf
standalone/nginx/nginx/conf.d/server.conf

Mostly a copy-paste from https://github.com/appsignal/nginx-metrics-standalone-test/, making use of the new stand-alone agent.
Part of #88 -- after this, archive the original repository and close the issue.

Add NGINX standalone test setup

---

elixir/phoenix-example/app/config/runtime.exs

This PR adds the logging backend implemented in https://github.com/appsignal/appsignal-elixir/pull/829 to the Phoenix test setup. The tests do not pass at the moment, as CI uses the `main` branch of the Elixir repository instead of the Elixir PR's `logger-backend` branch. They should pass on re-run after the Elixir PR is merged.

Add logging backend to Phoenix app

---

Rakefile

The `integrations:clone` command was not resetting the Elixir repositories, while the `integrations:reset` command had the wrong paths for some of those repositories.
Since we always reset after cloning, add the call to reset to the `clone_with_git` method.

Fix Elixir resets in integrations Rake commands

---

support/processmon/Dockerfile
support/processmon/build.sh

Use the sparse protocol for fetching the crates.io registry. Containers
kept running into an Out of Memory error (exit code 137) because it took
up more than 1GB of memory to update the registry.
With the sparse protocol I only saw the entire build peak around 500MB.
Add the `--rm` flag to clean up the container when the processmon binary
is copied from it.

Use sparse crates.io protocol in processmon build

---

nodejs/v3/express-apollo/app/src/appsignal.cjs
nodejs/v3/express-postgres/app/src/appsignal.cjs
nodejs/v3/express-yoga/app/src/appsignal.cjs
nodejs/v3/koa-mongo/app/src/appsignal.cjs
nodejs/v3/koa-mysql/app/src/appsignal.cjs
nodejs/v3/nestjs-prisma/app/appsignal.cjs
nodejs/v3/restify/app/src/appsignal.cjs

The Node.js apps no longer have the `pushApiKey` attribute preset when initializing their AppSignal clients.

Remove API key attribute from Node apps

---

elixir/plug/commands/console
nodejs/express-apollo/commands/console
ruby/linux-arm/commands/console
ruby/sinatra-gvltools/Dockerfile
ruby/sinatra-gvltools/app/Gemfile
ruby/sinatra-gvltools/app/app.rb
ruby/sinatra-gvltools/app/config.ru
ruby/sinatra-gvltools/app/config/appsignal.yml
ruby/sinatra-gvltools/app/processmon.toml
ruby/sinatra-gvltools/commands/console
ruby/sinatra-gvltools/commands/diagnose
ruby/sinatra-gvltools/commands/run
ruby/sinatra-gvltools/docker-compose.yml
ruby/sinatra/commands/console

Adds a test setup for Sinatra that uses Ruby 3.2 and adds GVLTools as a dependency for the project.
See https://github.com/appsignal/appsignal-ruby/pull/931 for context -- check out the branch in that PR in the integration to test this.

Add Sinatra + GVLTools test setup

---

ruby/rails7-sidekiq/app/app/controllers/examples_controller.rb
ruby/rails7-sidekiq/app/app/mailers/error_mailer.rb
ruby/rails7-sidekiq/app/app/views/examples/index.html.erb
ruby/rails7-sidekiq/app/app/views/layouts/application.html.erb
ruby/rails7-sidekiq/app/app/workers/active_job_error_worker.rb
ruby/rails7-sidekiq/app/config/application.rb
ruby/rails7-sidekiq/app/config/routes.rb

Allow for easier testing, rather than guessing the route.
Report an error that is not reraised by Rails's error handler.
Report an extra error in the Active Job jobs.
Show messages that are set by controller before redirects and such.
---
Tracking issue: https://github.com/appsignal/appsignal-ruby/issues/779

Rails error reporter

---

.semaphore/semaphore.yml
python/flask/Dockerfile
python/flask/app/.gitignore
python/flask/app/__appsignal__.py
python/flask/app/app.py
python/flask/app/processmon.toml
python/flask/app/requirements.txt
python/flask/commands/run
python/flask/docker-compose.yml

Flask application with the three basic endpoints provided by other apps. It doesn't include any additional dependencies such as data storages or background job managers, but can be used as a base to add those to new apps.
Part of: https://github.com/appsignal/appsignal-python/issues/9

Add Python flask test-setup

---

ruby/rails7-sidekiq/app/Gemfile.lock
ruby/rails7-sidekiq/app/app/controllers/workers_controller.rb

- Update Sidekiq to the latest version.
- Remove `.delay` methods of queuing jobs, they were removed in Sidekiq 7.
- Update Sidekiq internal error example to use RedisClient, the Redis gem Sidekiq switched to.

Update Sidekiq 7 test app

---

elixir/single-task/app/config/appsignal.exs
ruby/linux-arm/app/config/appsignal.yml
ruby/padrino/app/config/appsignal.yml
ruby/shoryuken/app/config/appsignal.yml
ruby/sinatra-gvltools/app/config/appsignal.yml
ruby/sinatra-puma/app/config/appsignal.yml
ruby/sinatra/app/config/appsignal.yml

Remove the debug option to remove the warning about using deprecated config options. We already configure `APPSIGNAL_LOG_LEVEL=trace` in the `appsignal.env` file.

Remove deprecated debug option from apps

---

Rakefile

If the log file doesn't exist yet, I don't want to have to keep retrying the command until it does. This extra `touch` makes sure the file exists and we can tail it.
I tried to combine the commands into one `docker-compose exec`, but then you need to specify the shell the container uses, which we don't know from the outside.
I tried to rely on the `APPSIGNAL_LOG_PATH=/tmp` env var set in `appsignal.env`, but had the same problem.

Create log file before tailing it

---

elixir/plug/app/lib/plug_example.ex

Add an endpoint that uses custom instrumentation to set params -- these params should not be overriden with appsignal/appsignal-elixir-plug#37.

Add custom instrumentation Plug endpoint

---

Rakefile
nodejs/v3/nestjs-prisma/app/.gitignore
nodejs/v3/nestjs-prisma/app/appsignal.cjs
nodejs/v3/nestjs-prisma/app/package-lock.json
nodejs/v3/nestjs-prisma/app/package.json
nodejs/v3/nestjs-prisma/app/processmon.toml
nodejs/v3/nestjs-prisma/app/src/prisma.service.ts
nodejs/v3/nestjs-prisma/commands/run

Part of appsignal/appsignal-nodejs#913. Requires appsignal/appsignal-nodejs#914 checked in as the integration.
---
Since the test setup app names map to the folder structure, we can
make use of the shell's autocomplete to find the right app, which
is neat.
But the shell will add a `/` to the end when it's a full match,
which makes Docker sad when running `app:down`. This fixes that.
Add it to `.gitignore` and to the `processmon.toml`.
It has been deprecated in Prisma 5. The upgrade manual suggests
using `process.on('beforeExit', ...)` instead.
The database should not be committed to the repository, but instead
initialised when the test setup is started.
Update both the `prisma` and `@prisma/client` packages to version
5.
For some reason, the `package.lock` in the test setup has its own …

Update Prisma to version 5

---

ruby/rails7-sidekiq/app/Gemfile.lock
ruby/rails7-sidekiq/app/config/environment.rb
ruby/rails7-sidekiq/app/config/initializers/logging.rb
ruby/rails7-sidekiq/app/config/initializers/sidekiq.rb

Make development/testing easier by logging to both the terminal/STDOUT and AppSignal (what we also want to test if it works). Without this change it would only log to AppSignal, which is delayed and not part of a local dev workflow.
Use ActiveSupport::Logger.broadcast to wrap loggers and send logs to multiple backends.
Move the Rails logger config from `config/environment.rb` to an initializer as documented in https://github.com/appsignal/appsignal-docs/pull/1453.

Log to both STDOUT and AppSignal in Sidekiq app

---

elixir/alpine-release/app/config/dev.exs
elixir/alpine-release/docker-compose.yml
elixir/phoenix-example/app/config/dev.exs
elixir/phoenix-example/docker-compose.yml
elixir/plug-oban/app/lib/application.ex
elixir/plug-oban/docker-compose.yml
elixir/plug/app/lib/plug_example/application.ex

Standardize all Elixir app ports to 4001, using the PORT env var, so it's the same how all apps listen to the same port on container host and when connected with a shell to the container.
Other apps are also (mostly) set up this way (we'll fix other ones later).

Standardize app ports for Elixir apps

---

nodejs/v3/nextjs-noappdir/README.md
nodejs/v3/nextjs-noappdir/app/src/pages/stargazers/[org]/[repo].tsx

Test how Next.js requests are reported from components using client side fetching. They don't include the `next.route` attribute.
[skip review]

Add example route to Next.js app with client fetch

---

nodejs/v3/nextjs-noappdir/Dockerfile
nodejs/v3/nextjs/Dockerfile

The latest NPM won't install on older Node.js versions.
[skip review]

Bump Node.js for Next.js app

---

elixir/phoenix-example/Dockerfile
ruby/jruby-rails6/Dockerfile
ruby/rails6-mongo/Dockerfile
ruby/rails6-mysql/Dockerfile
ruby/rails6-sequel/Dockerfile
ruby/rails6-shakapacker/Dockerfile
ruby/rails7-delayed-job/Dockerfile
ruby/rails7-sidekiq/Dockerfile

The Node.js 18 installer had a deprecation warning of 60 seconds from nodesource telling us this method is deprecated. Using the install method described at:
https://github.com/nodesource/distributions
Speed up the build by removing that dumb 60 second sleep.
[skip review]

Update Node.js install method

---

python/flask/app/app.py

This PR builds on top of the changes in #149. @tombruijn feel free to force-push anything you see fit :)
---
[Use metrics helpers in Flask](https://github.com/appsignal/test-setups/commit/728259a3cb7ff63264969ba11bbef0a967780cbb)
Instead of creating OpenTelemetry metrics manually, use the metrics
helpers implemented in https://github.com/appsignal/appsignal-python/pull/127.
This imports them from the root of the package, as implemented in
https://github.com/appsignal/appsignal-python/pull/132.

Use metrics helpers in Flask

---

python/django4-celery/app/appsignal_python_opentelemetry/views.py

We now have built-in helpers for tracing functionality, let's use those instead.
Also fix linter errors for missing double empty lines before/after methods.
[skip review]

Update Python django app to use built-in helpers

---

python/flask/app/requirements.txt

By default, pip will install the latest version, which is not supported by the OpenTelemetry integration yet.

Do not use Flask 3 yet

---

ruby/rails7-sidekiq/app/config/initializers/sidekiq.rb

Rails 7.1.1 removed the old `ActiveSupport::Logger.broadcast()` in favor of the new `ActiveSupport::BroadcastLogger`. Switch to that so that the test setup works with Rails 7.1.1 and above.

Use Rails 7.1+ broadcast logger

---

python/flask/app/app.py

Add an endpoint to the Flask test setup that causes an error to be raised (and reported to AppSignal) during the handling of another error.

Add nested errors endpoint

---

elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/controllers/page_controller.ex
elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/router.ex
elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/templates/page/index.html.eex

Adds an endpoint to the Phoenix test setup that performs a successful and a failing `Ecto.Multi` transaction.

Add `Ecto.Multi` transactions endpoint

---

python/django4-celery/app/appsignal_python_opentelemetry/wsgi.py

We're manually applying the WSGI instrumentation in `wsgi.py` in the Django test setup, alongside using `appsignal.start()` on `manage.py`. This results in event timelines that contain a WSGI span around the Django span.
For now, remove this, as this is not how we tell users to configure AppSignal in our documentation.
Screenshots of both timelines:
Note that, because the global HTTP extractor is not applied to Django spans, there are some attributes there that we should remove. See https://github.com/appsignal/appsignal-agent/pull/1081 for that.
Part of appsignal/appsignal-python#178, but not really.

Remove (unintentional?) WSGI instrumentation

---

nodejs/v3/express-apollo/app/src/appsignal.cjs
nodejs/v3/express-mongoose/app/src/appsignal.cjs
nodejs/v3/express-postgres/app/src/appsignal.cjs
nodejs/v3/express-redis/app/src/appsignal.cjs
nodejs/v3/express-yoga/app/src/appsignal.cjs
nodejs/v3/fastify/app/src/appsignal.cjs
nodejs/v3/koa-mongo/app/src/appsignal.cjs
nodejs/v3/koa-mysql/app/src/appsignal.cjs
nodejs/v3/nestjs/app/src/appsignal.cjs
nodejs/v3/nextjs/app/appsignal.cjs
nodejs/v3/remix/app/appsignal.cjs
nodejs/v3/restify/app/src/appsignal.cjs

We configure the app name using the `APPSIGNAL_APP_NAME` env var in the `docker-compose.yml` files. This overwrite in the file made the app report it using the wrong name.

Remove duplicate app names from Node.js configs

---

nodejs/v3/express-redis/app/package-lock.json
nodejs/v3/express-redis/app/src/app.ts

Debug custom log level easier in the future by adding it to the example.
- [Intercom conversation](https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/4356044/conversation/16410700259720#part_id=comment-16410700259720-21909542604)
- [Slack discussion](https://appsignal.slack.com/archives/C7XHXQ7N0/p1701328390811769)

Add Winston custom log levels example

---

nodejs/restify/app/package-lock.json
nodejs/restify/app/package.json
nodejs/restify/app/src/app.ts

Hopefully fixes the CI build. Removed the `next` argument of the `/slow` endpont, because restify told me it's no longer needed.
[skip review]

Upgrade restify app

---

ruby/sinatra/app/app.rb
support/processmon/Dockerfile

Some transitive dependency of `processmon` (`colored`?) only
supports Ruby 1.70 or higher on its latest version. Bump the Rust
version in the processmon builder image to the latest Rust version
to work around it.
Make `/error` report a nested error, showcasing support for the
error causes feature implemented in AppSignal for Ruby 3.5.0.

Add nested error to Sinatra test setup

---

python/django4-celery/app/__appsignal__.py
python/django4-celery/docker-compose.yml
python/fastapi/app/__appsignal__.py
python/fastapi/docker-compose.yml
python/flask/app/__appsignal__.py
python/flask/docker-compose.yml
python/starlette/app/__appsignal__.py
python/starlette/docker-compose.yml

Move all the config to env vars declared in the `docker-compose.yml` files, like we do for the other apps.
Remove `log_level` config from the config files, because it's configured in the `appsignal.env` file in the root already.
[skip review]

Update Python app AppSignal config location

---

elixir/alpine-release/Dockerfile
ruby/sinatra-alpine/Dockerfile

Use a smaller set of build dependencies for apps on Alpine Linux.
- Related docs update: https://github.com/appsignal/appsignal-docs/pull/1692
- Related issue: https://github.com/appsignal/appsignal-docs/issues/161
[skip review]

Update Alpine Linux build dependencies

---

Rakefile
nodejs/express-redis/commands/demo

Make it easy to run the demo command for integrations without having to run a bash/console command, navigate to the app directory and remember what the demo command is for an app.
I don't expect every app to have a demo command, but this makes it possible to easily add one to apps.
[skip review]

Add app demo command

---

ruby/rails6-mysql/app/Gemfile
ruby/rails6-mysql/app/Gemfile.lock
ruby/rails6-mysql/app/app/controllers/tests_controller.rb
ruby/rails6-mysql/app/app/views/tests/index.html.erb
ruby/rails6-mysql/app/config/routes.rb
ruby/rails7-postgres/app/Gemfile.lock
ruby/rails7-postgres/app/app/controllers/examples_controller.rb
ruby/rails7-postgres/app/app/views/examples/index.html.erb
ruby/rails7-postgres/app/config/routes.rb
ruby/sinatra-puma/app/Gemfile.lock
ruby/sinatra-puma/app/app.rb
ruby/sinatra-puma/commands/run

Allow us to test how our gem handles streaming requests.
Related PR: https://github.com/appsignal/appsignal-ruby/pull/1037

Add a streaming endpoint to Rails and Sinatra apps

---

ruby/sinatra-puma/app/app.rb
ruby/sinatra-puma/app/config/puma.rb

See https://github.com/appsignal/appsignal-ruby/pull/1057 for context.
It's kind of annoying to not see any output in the terminal and have
go look at this file instead. Standard output as standard output is
fine.

Add heartbeats endpoint to `sinatra-puma`

---

nodejs/express-apollo/commands/run
nodejs/express-mongoose/commands/run
nodejs/express-redis-alpine/commands/run
nodejs/express-redis/app/src/app.ts
nodejs/express-yoga/commands/run
nodejs/fastify/commands/run
nodejs/koa-mongo/commands/run
nodejs/koa-mysql/commands/run
nodejs/nestjs-prisma/commands/run
nodejs/nextjs-noappdir/commands/run
nodejs/nextjs/commands/run
nodejs/remix/commands/run
nodejs/restify/commands/run

This is a companion PR to the Heartbeats for Node.js one. No need to review it.
In order to be able to use the test setups to test against arbitrary
branches, they should not run `git checkout main` on the integration
repository.

Add heartbeat to `express-redis`

---

support/processmon/build.sh

Currently, the processmon build script explicitly sets --platform to linux/amd64, which breaks on arm:
~/work/appsignal/test-setups $ rake app=ruby/rails7-delayed-job app:up
Processmon not present. Building processmon...
Running 'cd support/processmon && ./build.sh'
[+] Building 0.5s (5/7)                                                           docker:desktop-linux
=> [internal] load build definition from Dockerfile                                              0.0s
=> => transferring dockerfile: 219B                                                              0.0s
=> [internal] load metadata for docker.io/library/rust:1.74.1-alpine3.17                         0.4s
=> [internal] load .dockerignore                                                                 0.0s
=> => transferring …

Remove the explicitly set --platform when building processmon

---

python/flask/app/app.py

No need to review if this is not a good use of your time. Will merge without reviews.
This is a companion PR to appsignal/appsignal-python#203.
Add a `/heartbeat` endpoint to the `flask` test setup that uses the Python integration's heartbeat feature to send a heartbeat.

Add heartbeats to `flask` test setup

---

python/flask/app/app.py

Reverts appsignal/test-setups#197 so the build isn't broken until https://github.com/appsignal/appsignal-python/pull/203 is merged.
[skip review]

Revert "Add heartbeats to `flask` test setup"

---

nodejs/koa-mysql/docker-compose.yml
ruby/jruby-rails6/Dockerfile
ruby/jruby-rails6/app/Gemfile

Buncha things broke, buncha things fixed. Life goes on.
The test setup uses the `mysql` library, which is not and will not
be compatible with the new authentication protocols in MySQL 8.4.
(The `mysql2` library does support those)
A newer version of `nio4r` does not play nicely with Java 8. Upgrade
to Java 11.

Fix test setups

---

ruby/rails7-sequel/app/Gemfile
ruby/rails7-sequel/app/Gemfile.lock
ruby/rails7-sequel/app/app/components/example_component.rb
ruby/rails7-sequel/app/app/views/users/index.html.erb
ruby/rails7-sequel/app/config/application.rb

Add the `view_component` gem and render a ViewComponent-based component in an existing view. See [event formatter PR for context](https://github.com/appsignal/appsignal-ruby/pull/1082).

Add ViewComponent-based component

---

.semaphore/semaphore.yml
ruby/hanami2-postgres/app/app/action.rb
ruby/hanami2-postgres/app/app/actions/errors/show.rb
ruby/hanami2-postgres/app/app/actions/slow/show.rb
ruby/hanami2-postgres/app/config/app.rb
ruby/hanami2-postgres/app/config/routes.rb
ruby/hanami2-postgres/app/processmon.toml

The Hanami app wasn't added to the CI build yet and it didn't include routes for an example error and slow endpoint.
[skip review]

Add Hanami app to the CI build

---

Rakefile

This fixes an issue where, after running `integrations:clone`, you end up with a newer version of the integration's source code, but an old version of the agent within it.
[skip review]

Remove old agent artifacts on integrations clone

---

nodejs/nestjs-prisma/app/processmon.toml

When booting the NestJS + Prisma test setup, the TypeScript code is compiled. Processmon picks up the outcome of the build as a change and triggers the build to restart, getting stuck in a loop.
I'm not sure why this doesn't happen in CI. This behaviour may be tied to the versions of the dependencies used -- I found this while testing it with `prisma@5.14.0`. Nonetheless, having Processmon ignore the `dist` folder makes sense.
[skip review]

Avoid boot loop on NestJS + Prisma build

---

nodejs/nestjs-prisma/app/prisma/migrations/20240704123353_init/migration.sql

Generated automatically from the schema with `npx prisma migrate dev --name init`.
I'm not sure how this ever worked. Perhaps I had a migrated database locally, but I never actually committed the migration. It might also have to do with the newer version of Prisma I'm using to test this.
[skip review]

Add Prisma migration

---

Rakefile

Fix issue with builds failing because the tests setups don't work against the Ruby gem's develop branch.
[skip review]

Clone Ruby integration's main branch

---

nodejs/nextjs-13-app/app/next.config.js
nodejs/nextjs-13-app/app/package-lock.json
nodejs/nextjs-13-app/app/package.json
nodejs/nextjs-13-pages/app/next.config.js
nodejs/nextjs-13-pages/app/package-lock.json
nodejs/nextjs-13-pages/app/package.json
nodejs/nextjs-14-app/app/next.config.mjs
nodejs/nextjs-14-app/app/package-lock.json
nodejs/nextjs-14-app/app/package.json
nodejs/nextjs-14-pages/app/next.config.mjs
nodejs/nextjs-14-pages/app/package-lock.json
nodejs/nextjs-14-pages/app/package.json

For source-mapped backtraces to be emitted for Next.js backend errors
when Next.js is running in production mode, the webpack configuration
needs to be tweaked in order to emit backtraces, and the
`--enable-source-maps` flag needs to be passed to the Node.js runtime
when starting the Next.js application, using the `NODE_OPTIONS`
environment variable.
The Next.js test setups, due to a Webpack limitation, do not use the
source code of the integration at `nodejs/integration`, instead
installing it from the NPM servers.
Due to this, it makes sense for its bound to be set to `latest`, to
prevent accidentally testing against a very old version of the
integration.

Next js production backend source maps

---

ruby/sinatra-puma/app/app.rb

See https://github.com/appsignal/appsignal-ruby/pull/1293.

Add heartbeat check-ins `sinatra-puma` endpoint

---

nodejs/nextjs-13-app/Dockerfile
nodejs/nextjs-14-app/Dockerfile
nodejs/nextjs-14-pages/Dockerfile

Some of their transitive dependencies are no longer happy running on Node 18, which will be EOL in a few months anyway.
This fixes [the test failures on `main` CI](https://appsignal.semaphoreci.com/workflows/7094815e-70d7-4e85-b73d-194dddc06dde?pipeline_id=0386a25a-a3ad-4d3f-927d-50cb87810199) for the `nodejs/next-13-app`, `nodejs/next-14-app` and `nodejs/next-14-pages` test setups.

Update Next.js setups to Node 20

---

ruby/webmachine1/Dockerfile
ruby/webmachine2/Dockerfile

This fixes an issue where `gem update --system` fails because the
latest RubyGems version does not support Ruby 3.0.
---
Update the Webmachine test setups to Ruby 3.2.2.
---
This fixes [the test failures on `main` CI](https://appsignal.semaphoreci.com/workflows/7094815e-70d7-4e85-b73d-194dddc06dde?pipeline_id=0386a25a-a3ad-4d3f-927d-50cb87810199) for the `ruby/webmachine1` and `ruby/webmachine2` test setups.

Update Webmachine test setups to Ruby 3.2.2

---

ruby/rails6-mongo/Dockerfile

This test setup runs on Ruby 3.0.3, which is not supported by RubyGems 3.6.0.
Attempting to upgrade this test setup to Ruby 3.2.2, like the other Rails 6 test setups (see #247), surfaced some issue with Psych that I did not care to look into at this time.
---
This fixes [the test failures on main CI](https://appsignal.semaphoreci.com/workflows/7094815e-70d7-4e85-b73d-194dddc06dde?pipeline_id=0386a25a-a3ad-4d3f-927d-50cb87810199) for the `ruby/rails6-mongo` test setup.

Keep Rails 6 + Mongo RubyGems on 3.5.23

---

Rakefile

This will make it easier to track the range of possible changes that are responsible for a specific failure on the test setups' scheduled CI.

Print which commit was cloned

---

ruby/rails8-sidekiq/app/config/initializers/logging.rb
ruby/rails8-sidekiq/app/config/initializers/sidekiq.rb

Copy the logging initialisers for Rails and Sidekiq from the `ruby/rails7-sidekiq` test setup into the `ruby/rails8-sidekiq` test setup.
In the future, this might help us detect issues like appsignal/appsignal-ruby#1348 before they impact our customers.

Add logging initialisers to Rails 8

---

elixir/plug-ecto/app/lib/plug_example.ex

[skip review]
Added a transaction endpoint to Plug + Ecto, making it easier to see what Ecto transactions look like. I thought I had done this back when I worked on [improving Ecto transactions](https://github.com/appsignal/appsignal-elixir/pull/902), but I guess I didn't.

Add transaction endpoint to Plug + Ecto

---

ruby/rails8-sidekiq/app/Gemfile
ruby/rails8-sidekiq/app/Gemfile.lock
ruby/rails8-sidekiq/app/app/controllers/examples_controller.rb

See https://github.com/appsignal/appsignal-ruby/pull/1364. [skip review]
Add the `ownership` gem to the Rails 8 + Sidekiq test setup. Set the examples controller to be owned by the "examples" group.

Add Ownership to Rails 8 + Sidekiq

---

ruby/rails8-sidekiq/app/config/initializers/logging.rb

Avoid confusion why things aren't working properly, like not silencing logs, by using the method described in our docs.
Following the steps in:
https://docs.appsignal.com/logging/integrations/ruby.html#using-multiple-logging-backends

Set up Rails 8 app logger according to our docs

---

python/django5-celery-collector/app/appsignal_python_opentelemetry/opentelemetry.py
python/django5-celery-collector/app/appsignal_python_opentelemetry/settings.py
python/django5-celery-collector/app/tasks.py

Instead of repeating the config per service (Django and Celery), create one shared config file and require it in each service. While still allowing us to customize the service name.
Docs PR that introduces this: https://github.com/appsignal/appsignal-docs/pull/2381

Configure Python app with shared config file

---

elixir/phoenix-collector/app/config/config.exs
nodejs/express-postgres-collector/app/src/opentelemetry.cjs
python/django5-celery-collector/app/appsignal_python_opentelemetry/opentelemetry.py
ruby/rails8-sidekiq-collector/app/config/initializers/opentelemetry.rb

Add this useful config option to the test app so we can test if it works once we implemented the whole feature.
Part of https://github.com/appsignal/appsignal-collector/issues/182
[skip review]

Add app path config option to OTel apps

---

elixir/phoenix/app/assets/css/app.css
elixir/phoenix/app/assets/js/app.js
elixir/phoenix/app/lib/appsignal_phoenix_example_web/live/demo_live.ex

The live view demo didn't report any live view data, probably because of some optimization.
Make the component interactable to report live view events.
Disable the Phoenix top bar code because it threw an error.
[skip review]

Add working live view example

---

java/spring-agent-collector/app/agent.properties
java/spring-native-collector/app/src/main/java/io/opentelemetry/example/graal/OpenTelemetryConfig.java
nodejs/express-postgres-collector/app/processmon.toml
nodejs/express-postgres-collector/app/src/opentelemetry.cjs
python/django5-celery-collector/app/appsignal_python_opentelemetry/opentelemetry.py

See https://github.com/appsignal/appsignal-collector/pull/214.
---
This fixes an issue where Processmon gets stuck in a restart loop
because it detects the consequences of its own command, which
re-creates the files in `/dist`, as changes.
Remove metric aggregation temporality adjustments from any collector
test setups that have them. This simplifies the OpenTelemetry setup
for test setups that export metrics.
---
Is this a change we actually want to do? Data accuracy is slightly better for delta histograms over cumulative histograms, as minimum and maximum values are guaranteed to be usable explicit values in cumulative histograms -- but it doesn't make a big difference, especially if the metrics transmission interval is short. If it is, then:

Remove metric aggregation temporality adjustments

---

elixir/phoenix/app/config/appsignal.exs
elixir/phoenix/app/config/config.exs

This config seems to be missing. Add it.
[skip review]

Configure the OTP app option for Elixir Phoenix

---

php/laravel-collector/app/routes/web.php

Test tags quickly because they're already set in the test app.
[skip review]

Add example tags to the PHP app

---

ruby/rails8-sidekiq/app/config/application.rb

For some reason the app wasn't configured to use Sidekiq for Active Job jobs, so it ran the Active Job jobs in the Rails thread.
Change the config so we can test Active Job with Sidekiq.
[skip review]

Configure Sidekiq as Active Job adapter in Rails 8

---

php/laravel-collector/app/app/Jobs/ExampleJob.php
php/laravel-collector/app/composer.lock
php/laravel-collector/app/routes/web.php
php/laravel-collector/commands/run
php/laravel-collector/docker/README
php/laravel-collector/docker/supervisord.conf

This implements a `/queue` endpoint which sends a job to be executed in the Laravel worker queue, and adds a separate PHP process to `supervisord`, which is used internally by the Docker image, to process jobs in said queue.
This is a step towards improving our support for Laravel's worker queues, which is... not great.

Laravel worker queue

---

elixir/phoenix-collector/docker-compose.yml
go/beego-mod-otel/docker-compose.yml
go/beego/docker-compose.yml
go/go-gin-mysql-collector/docker-compose.yml
go/go-gin-mysql/docker-compose.yml
go/gorilla-mux-mysql-redis-mongo-collector/docker-compose.yml
go/gorilla-mux-mysql-redis-mongo/docker-compose.yml
java/spring-agent-collector/docker-compose.yml
java/spring-native-collector/docker-compose.yml
javascript/react-vite-collector/docker-compose.yml
nodejs/express-postgres-collector/docker-compose.yml
php/laravel-collector/docker-compose.yml
python/django5-celery-collector/docker-compose.yml
ruby/rails7-postgres/docker-compose.yml
ruby/rails8-sidekiq-collector/docker-compose.yml
standalone/nginx/docker-compose.yml
vector/mongodb/docker-compose.yml

This avoids confusion when, for example, the key is set in the `appsignal_key.env` file, but the endpoint is set on the `appsignal.env` file.

Use both `appsignal.env` and `appsignal_key.env` files

---

ruby/rails8-sidekiq/app/Gemfile
ruby/rails8-sidekiq/app/app/controllers/examples_controller.rb
ruby/rails8-sidekiq/app/config/initializers/logging.rb

I've not enabled it by default because we don't need it. But it's good to have some example code in the app ready to go.
[skip review]

Add Semantic logger code for Rails app

---

php/laravel-collector/app/.env.example
php/laravel-collector/app/bootstrap/app.php
php/laravel-collector/app/bootstrap/instrumentation.php
php/laravel-collector/commands/run
php/laravel-collector/docker-compose.yml

In `bootstrap/app.php`, we manually call the `LoadEnvironmentVariables` bootstrapper on the app instance, then initialise the OpenTelemetry instrumentation, then return the app. This makes it possible to configure AppSignal with the same environment variables that the Laravel application will use, while also initialising OpenTelemetry early enough that Laravel routes are instrumented.
The instrumentation file itself is generic and _should_ work with any other PHP framework, though this of course hasn't been tested. It may be worth building a test setup with Symfony, or if not, one using Slim, and optionally Dotenv.

Configure laravel with code from `.env`

---

go/beego/Dockerfile
python/django4-celery/Dockerfile
python/django5-celery-collector/Dockerfile
python/django5-celery/Dockerfile
python/fastapi/Dockerfile
python/flask/Dockerfile
python/starlette/Dockerfile

The buster update server is returning errors on update. Update Debian to the next version to fix it.
[skip review]

Fix apps using Debian buster by updating Debian

---

ruby/hanami2-postgres/app/Gemfile.lock
ruby/hanami2-postgres/app/config/db/structure.sql

It's broken because of the error message below. Fix it by updating bundler.
```
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:312:in `load': cannot load such file -- /usr/local/bundle/gems/bundler-2.5.22/lib/gems/bundler-2.5.22/exe/bundle (LoadError)
from /usr/local/lib/ruby/site_ruby/3.3.0/rubygems.rb:312:in `activate_and_load_bin_path'
from /usr/local/bundle/bin/bundle:25:in `<main>'
```
[skip review]

Update Bundler in Hanami 2 app to fix CI

---

go/go-gin-mysql-collector/app/main.go

Don't get the context three times, but once and assign it to a variable.
We had a resource and sdkresource import. Use just one.
Make clear what's from our installer copy-pasted and what custom things we added for the test app, so it's easier to compare in the future when updating our instructions.
It was pointed out to us that our use of log.Fatal calls was not including the actual error.

Go app configuration improvements

---

ruby/rails8-sidekiq-collector/app/app/controllers/examples_controller.rb

Otherwise we don't see the error reported to AppSignal.
[skip review]

Ruby app should raise error on error cause route

---

nodejs/express-redis/app/package-lock.json
nodejs/express-redis/app/package.json

The node integration uses a more recent version of `winston`, which requires a newer version of `logform`, which in turn has added a symbol index signature to the `TransformableInfo` interface.
This change updates the versions of `winston` to fix the mismatch, and `@types/node` to stop `tsc` from complaining about missing `fetch`.

Fix `winston` version mismatch in `nodejs/express-redis` app

---

nodejs/express-bullmq/commands/run
nodejs/express-rabbitmq/commands/run
nodejs/express-redis/commands/run
php/symfony-collector/commands/run

Add `set -eu` to exit the run script if a child process ran into a problem or if a variable was undefined.

Don't start if an error occurred during app start

---

.github/workflows/ci.yml

Add a timeout of 10 minutes for test jobs.
Right now jobs have the default timeout, which is 360 minutes. Recently, a Node.js test job ran for 2h 20m 13s. 
See https://github.com/appsignal/test-setups/actions/runs/18198404643/job/51810713493.
Most test jobs finish within 2-3 minutes, the longest being PHP tests, running for 4 minutes.

Add a timeout to github test jobs
